AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Resource Name
      Parameters:
      - ResourceName

Parameters:
  ResourceName:
    ConstraintDescription: Resource Name
    Default: slsblog
    Description: Resource Name
    Type: String
    AllowedPattern: "[a-z/-]*"

Resources:
  SLSBlogDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ResourceName}-DB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: pagename
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: updateDate
          AttributeType: S
        - AttributeName: createDate
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: pagename
          KeyType: RANGE
#      ProvisionedThroughput:
#        ReadCapacityUnits: 1
#        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: updateIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: updateDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: createIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: createDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  StaticSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ResourceName}-bucket
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
            AllowedHeaders:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  StaticSiteS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticSite
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
            - s3:GetObject
            Resource:
              Fn::Join: ["", ["arn:aws:s3:::",{"Ref": "StaticSite"},"/*"]]
