service: slsblog-adminpage

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        # default
        - logs:CreateLogStream # default
        - logs:PutLogEvents # default
        # dynamodb
        - "dynamodb:*"
      Resource:
        - '*'
        
custom:
  resourceName: slsblog-testsite
  websiteName: SLSBlog
  
package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  serverlessTest:
    handler: lambda.handler
    environment:
      DB_NAME: ${self:custom.resourceName}-DB
      SITE_NAME: ${self:custom.websiteName}管理ページ
      BASIC_AUTH_USERNAME: username
      BASIC_AUTH_PASSWORD: password
    events:
      - httpApi:
          path: /
          method: '*'
      - httpApi:
          path: /{proxy+}
          method: '*'