service: serverless-express-test

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        # default
        - logs:CreateLogStream # default
        - logs:PutLogEvents # default
        # dynamodb
        - "dynamodb:*"
      Resource:
        - '*'

package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  serverlessTest:
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: '*'
      - httpApi:
          path: /{proxy+}
          method: '*'